### ISSUE TITLE
Network configuration

### ISSUE THREAD

**Issue by Cornu** [mirrexagon/espressobin-nix#2]
The Espressobin comes up with three network interfaces:

- eth0
- wan@eth0
- lan0@eth0
- lan1@eth0

Enabling DHCP only on wan@eth0 doesn't work, we need DHCP also on eth0, but then ipv4 is broken, because two interfaces have the same address? Manually deleting the assigned address on eth0 solves the problem.

So what's the best way to configure these interfaces on NixOS?

I found this issue https://github.com/systemd/systemd/issues/7478, is this related?

**Comment by mirrexagon** [comment]
Apologies, I didn't see this until today!

I haven't tested it recently, but this is what I did to solve the DHCP-related issues I had:

```nix
  # Make sure the internal eth0 interface doesn't get routes set that override the actual external interfaces.
  networking.dhcpcd.denyInterfaces = [ "eth0" ];

  # The above means that the ethernet interfaces don't get brought up automatically, we bring them up here.
  networking.localCommands = ''
    ip link set eth0 up
    ip link set wan up
    ip link set lan0 up
    ip link set lan1 up
  '';
```

**Comment by Cornu** [comment]
Thanks for the reply :)

My solution, with the help from the issue above, was using systemd networkd.

``` Nix
networking.useNetworkd = true;
systemd.network.networks."40-eth0" = {
  matchConfig.Name = "eth0";
  networkConfig.LinkLocalAddressing = "ipv6";
};
networking.interfaces.wan.useDHCP = true;
systemd.network.networks."40-wan".networkConfig.BindCarrier = [ "eth0" ];
```

Not the cleanest solution. Both the `LinkLocalAdressing` and `BindCarrier` is needed.

**Comment by edrex** [comment]
Thanks for sharing @Cornu. I just posted my gateway router confg [here](https://github.com/edrex/nixos-config/blob/master/hosts/whitecanyon/router.nix).

**Comment by mirrexagon** [comment]
I've now tried a scripted (non-systemd-networkd) configuration without any of these hacks with U-Boot 2024.10 (with MAC addresses set in the U-Boot environment) and Linux 6.6 and it seems to just work. I've updated the README accordingly.
