### ISSUE TITLE
U-Boot default environment doesn't leave enough space for ramdisk for newer kernel

### ISSUE THREAD

**Issue by mirrexagon** [mirrexagon/espressobin-nix#8]
When trying to boot at least 6.11, I get a message that "RD image overlaps OS image". According to https://github.com/NixOS/nixpkgs/issues/295660, we probably need to move the kernel and ramdisk and perhaps FDT RAM load addresses around so that there's enough space.

I'm not sure how you determine what areas of RAM are okay to use for this.

**Comment by TurboPunk** [comment]
I still seem to have this issue on a recent aarch64 nixos-sd-image

Any idea what could be wrong?

```
Scanning scsi 0:2...         
Found /boot/extlinux/extlinux.conf                                                           
Retrieving file: /boot/extlinux/extlinux.conf
------------------------------------------------------------                                 
1:      NixOS - Default      
Enter choice: 1:        NixOS - Default                                                      
Retrieving file: /boot/extlinux/../nixos/zqd0d5sv8jl083dk54v156fr62p89k7w-linux-6.6.61-Image
Retrieving file: /boot/extlinux/../nixos/h9gnlwadaya9m6ax61fmal6p3zl3yyqj-initrd-linux-6.6.61-initrd
append: init=/nix/store/2f0kbwqmivfiv683rnzwb5fk2zpbj5fh-nixos-system-nixos-24.05.6668.e8c38b73aeb2/init console=ttyS0,115200n8 console=ttyAMA0,115200n8 console=tty0 nohibernate loglevel=
7                 
Retrieving file: /boot/extlinux/../nixos/zqd0d5sv8jl083dk54v156fr62p89k7w-linux-6.6.61-dtbs/marvell/armada-3720-espressobin-v7.dtb
ERROR: RD image overlaps OS image (OS=7000000..b330000)
```

**Comment by mirrexagon** [comment]
Oh, I changed the ramdisk address from 0xa000000 to 0xb000000 which worked for me, but your error message shows the OS/kernel image goes past that address to 0xb330000. You can try booting to the U-Boot console and moving the ramdisk address up even more:

- `env set ramdisk_addr_r 0xc000000`
- `env save`

and then try booting again (eg. type `reset`).
